POST  http://localhost:3001/api/user/register
Content-Type: application/json

{
    "firstname" :"John",
    "lastname" :  "Doe",
   "email" : "vanina",
    "hash" :   "vanina",
   "address"  : "String",
    "phone"  : " 23456677"
}

###

POST  http://localhost:3001/api/posts
Content-Type: application/json

{
   "type" : "ALERT",
   "userId" : "853ea835-0cfd-4365-bfd6-90b9f2bab81b"
}

###

GET http://localhost:3001/api/user